using System;
using System.Collections.Generic;
using System.Text;

namespace BEZNgCore.iGuestData.Dtos
{
    public class PublishInvoiceData
    {
        //public string RefID { get; set; }          // Unique identifier of the invoice message (UUID)
        //public string TransactionID { get; set; }  // Transaction ID of the invoice, usually the same as RefID
        //public string InvSeries { get; set; }      // Invoice series
        //public string InvoiceData { get; set; }    // The detailed invoice data in Base64 encoding (XML document)
        //public bool IsInvoiceCalculatingMachine { get; set; } // Indicates if invoice is generated by a calculating machine
        //public bool IsSendEmail { get; set; }      // Whether to send the invoice email after successful issuance
        //public string ReceiverName { get; set; }   // Recipient's name
        //public string ReceiverEmail { get; set; } // Recipient's email address, separated by ';'
    }
}
